name: Auto Assign Reviewer on File Change

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if monitored files changed
        id: check
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          git fetch origin $BASE
          CHANGED=$(git diff --name-only origin/$BASE...${{ github.sha }} || echo "")
          echo "$CHANGED"
          MATCH=false

          while read -r FILE; do
            case "$FILE" in
              "test/param_defaults_All.json" | \
              "test/param_defaults.json" | \
              "Space Folder/Space file name - JSON.txt")
                MATCH=true
                break
                ;;
            esac
          done <<< "$CHANGED"

          echo "file_changed=$MATCH" >> $GITHUB_OUTPUT

      - name: Assign reviewer via GitHub API
        if: steps.check.outputs.file_changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers": ["Shimi-Bitton"]}'
