name: Auto Assign Reviewer on Specific File Changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files from PR
        id: filecheck
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILES=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
            | jq -r '.[].filename')

          echo "Changed files:"
          echo "$FILES"

          MATCH=false

          while read -r FILE; do
            case "$FILE" in
              "test/param_defaults_All.json" | \
              "test/param_defaults.json" | \
              "Space Folder/Space file name - JSON.txt")
               MATCH=true
                break
                ;;
            esac
          done <<< "$FILES"

          echo "file_changed=$MATCH" >> $GITHUB_OUTPUT

      - name: Assign reviewer via GitHub API
        if: steps.filecheck.outputs.file_changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Assigning reviewer Shimi..."
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers": ["Shimi-Bitton"]}'
