---
name: New CI for Simple Project
on:
  push:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch: null
jobs:
  Code-Check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: >
          lscpu

          free -g

          sudo apt update && sudo apt install git cmake g++ libgtest-dev # installing gtest

          cd /usr/src/googletest

          sudo cmake .

          sudo make

          sudo cp lib/*.a /usr/lib

          sudo apt install python3-pip

          pip install pygments
      - name: cppcheck
        run: >
          git clone https://${{ secrets.PAT_TOKEN
          }}@github.com/IRPSystems/Dynamic_Project.git Dynamic_Core

          #GIT_TRACE=1 GIT_CURL_VERBOSE=1 git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/IRPSystems/Dynamic_Project.git Dynamic_Core

          cd Dynamic_Core && mkdir SRC

          cppcheck --enable=all --xml --xml-version=2 --library=googletest . 2>report-src.xml

          ../htmlreport --source-dir=. --title=Dynamic_Core-Report --file=report-src.xml --report-dir=SRC_RPT

          zip -r ../Dynamic_Core-Report.zip ./SRC_RPT/
      - name: Upload the ZIP file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: Dynamic_Core-Report.zip.zip
