# Written by Shimon Bitton, FEB-2025.
# This CI runs Compilation and Ctest when push event submitted on master/develop and all branches called feature*
# Also it runs at night
# and to Doxygen part runs on specific branches

name: New CI for Simple Project

on: 
  push:
    branches:
      - main  # Runs on main branch (master)
      - develop # Runs on develop
      - feature/*  # Runs on all feature branches (optional)

  workflow_dispatch:      # Allow to run it manually.

  #schedule:
   # - cron: "0 20 * * 0-4"  # Nightly config - Runs at 20:00 UTC from Sunday (0) to Thursday (4)


jobs:
  Code-Check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: |
           lscpu
           sudo apt update && sudo apt install cmake g++ libgtest-dev # installing gtest
           cd /usr/src/googletest
           sudo cmake .
           sudo make
           sudo cp lib/*.a /usr/lib
           sudo apt install python3-pip
           pip install pygments
    - name: cppcheck
      run: |
         git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/IRPSystems/Dynamic_Core.git Dynamic_Core
         cd Dynamic_Core && mkdir SRC
         cppcheck --enable=all --xml --xml-version=2 --library=googletest . 2>report-src.xml
         ../htmlreport --source-dir=. --title=Dynamic_Core-Report --file=report-src.xml --report-dir=SRC_RPT
         zip -r ../Dynamic_Core-Report.zip ./SRC_RPT/

    - name: Upload the ZIP file as an artifact
      uses: actions/upload-artifact@v4
      with:
          name: report
          path: Dynamic_Core-Report.zip.zip
