name: Commit Message Validation - Check for Jira Issue Key in Commit Message 

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

jobs:
  check_commit_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message for Jira issue key
        run: |
          # Define Jira project keys
          jira_keys="DO-|SW-|CTRL-|ALGO-|EMBD-|TG4-|TG5-|D1-|1D-"
          
          # Regex pattern to match Jira issue keys
          jira_key_regex="($jira_keys[0-9]+)"
          
          # If it's a push event (to main/master), check the latest commit
          if [[ $GITHUB_EVENT_NAME == "push" ]]; then
            # Get the latest commit message
            commit_message=$(git log -1 --pretty=%B)
            if [[ ! "$commit_message" =~ $jira_key_regex ]]; then
              echo "Error: Commit message '$commit_message' is missing a valid Jira issue key."
              exit 1
            fi
          else
            # For pull requests, check the commits in the PR
            for commit in $(git log --format="%s" origin/main..HEAD); do
              if [[ ! "$commit" =~ $jira_key_regex ]]; then
                echo "Error: Commit message '$commit' is missing a valid Jira issue key."
                exit 1
              fi
            done
          fi
